services:
  algod:
    build:
      context: ./follower-image
      dockerfile: ./Dockerfile
      args:
        NETWORK: ${NETWORK}
    image: "xarmian/voit-follower"
    container_name: voit-follower
    volumes:
     - ./follower-data:/algod/data
    environment:
     - NETWORK=${NETWORK}
     - TOKEN=${TOKEN}
     - ADMIN_TOKEN=${ADMIN_TOKEN}
     - VIRTUAL_HOST=${NODE_VIRTUAL_HOST}
     - VIRTUAL_PORT=8080
     - LETSENCRYPT_HOST=${NODE_VIRTUAL_HOST}
    restart: unless-stopped
    networks:
     - voi-idx
     - nginx-proxy

  indexer-db:
    image: postgres:14-alpine
    container_name: voit-postgres
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
     - voi-idx

  conduit:
    image: algorand/conduit
    container_name: voit-conduit
    volumes:
     - ./conduit.yml:/etc/algorand/conduit.yml
    restart: unless-stopped
    networks:
     - voi-idx
    depends_on:
     - algod

  indexer:
    container_name: voit-indexer
    image: algorand/indexer
    expose:
     - 8980
    environment:
      PORT: "8980"
      INDEXER_POSTGRES_CONNECTION_STRING: "host=voit-postgres port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
      INDEXER_ENABLE_ALL_PARAMETERS: "true"
      INDEXER_DATA: "/data"
      INDEXER_API_TOKEN: "${INDEXER_API_TOKEN}"
      INDEXER_MAX_TRANSACTIONS_LIMIT: 9999999
      VIRTUAL_HOST: "${INDEXER_VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${INDEXER_VIRTUAL_HOST}"
    restart: unless-stopped
    networks:
     - voi-idx
     - nginx-proxy
    command: daemon --data-dir /data
    depends_on:
      - indexer-db

networks:
  voi-idx: {}
  nginx-proxy: {}
