#!/bin/bash

# Initialize flags
build=
nginx=

# Parse command line arguments
for arg in "$@"
do
    case $arg in
        --build)
            build=1
            shift # Remove --build from processing
            ;;
        --nginx)
            nginx=1
            shift # Remove --nginx from processing
            ;;
    esac
done

# Determine config file based on NETWORK in .env
source .env
if [[ "$NETWORK" == "voitest-v1.0" || "$NETWORK" == "voimain-v1.0" ]]; then
    export CONFIG_FILE="config-${NETWORK}.json"
else
    export CONFIG_FILE="config-ALGORAND.json"
fi

echo "Starting Algod, Postgres, Conduit, Indexer"
if [ "$build" = "1" ]; then
    docker compose build --build-arg CONFIG_FILE=$CONFIG_FILE
    docker compose up -d
else
    docker compose up -d
fi

if [ "$nginx" = "1" ]; then
    echo "Starting Nginx, Acme"
    docker compose -f docker-compose-nginx.yml up -d
fi

